### ISSUE TITLE
java/intellij

### ISSUE THREAD

**Issue by t6** [t6/wip-ports#1]
The port works right now (https://freshports.org/java/intellij), but some features are unavailable due to 
- [x] <s>missing Pty4J support (see traff/pty4j#22).</s>
- [x] <s>update port to patch in Pty4J fork</s>
- [x] <s>needing a fsnotifier replacement (see https://github.com/JetBrains/intellij-community/tree/master/native/fsNotifier and maybe https://github.com/skirge/fsnotifier-freebsd ?),</s>
- [x] <s>and missing breakgen support (see https://github.com/JetBrains/intellij-community/tree/master/native/breakgen)</s>

**Comment by t6** [comment]
Unfortunately traff/pty4j#22 does not work, so I created a fork of Pty4J at https://github.com/t6/pty4 which contains a working version for FreeBSD.  `libpty.so` (the required native component) needs to be build with  `gmake -C native LINUX=freebsd CC=cc linux_x86_64` and is then available in `os/`

I'm able to get a working terminal in IntelliJ now by monkey patching the bundled jars. Next step: Update the port to do the patching automatically.

**Comment by t6** [comment]
for fsnotifier replacement set property `idea.filewatcher.executable.path` in `bin/idea.properties` if you have one. See https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/openapi/vfs/impl/local/NativeFileWatcherImpl.java#L149

**Comment by jirib** [comment]
I can confirm that fsnotifier works on OpenBSD, thus when the file content is modified outside of idea fsnotifier discovers it and idea reloads the file.

**Comment by t6** [comment]
Yes, it works on FreeBSD too, but I found an issue that needs fixing I think. Can you try this on OpenBSD? https://github.com/idea4bsd/fsnotifier/issues/1

**Comment by t6** [comment]
Closing this. Everything else in https://github.com/idea4bsd/idea4bsd/issues
